CREATE ROLE root WITH LOGIN PASSWORD 'root';

CREATE ROLE pooleruser WITH LOGIN PASSWORD 'pooleruser' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE service_monitor_db
GRANT ALL PRIVILEGES ON DATABASE service_monitor_db TO root
GRANT ALL PRIVILEGES ON DATABASE service_monitor_db TO pooleruser