version: "3"
services:
  database:
    image: "postgres:13.4"
    container_name: "service_monitor_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
